
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CheckboxForm extends javax.swing.JFrame implements ActionListener {

    public CheckboxForm() {
        initComponents();
        setLocationRelativeTo(null);
        addActionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox5 = new javax.swing.JCheckBox();
        jPanel = new javax.swing.JPanel();
        labelChick = new javax.swing.JLabel();
        labelPuppy = new javax.swing.JLabel();
        labelDuck = new javax.swing.JLabel();
        labelRabbit = new javax.swing.JLabel();
        labelCat = new javax.swing.JLabel();
        labelPig = new javax.swing.JLabel();
        cbChick = new javax.swing.JCheckBox();
        cbPuppy = new javax.swing.JCheckBox();
        cbDuck = new javax.swing.JCheckBox();
        cbCat = new javax.swing.JCheckBox();
        cbRabbit = new javax.swing.JCheckBox();
        cbPig = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox5.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pet");
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn pet của bạn", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel.setForeground(new java.awt.Color(204, 204, 204));
        jPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel.setVerifyInputWhenFocusTarget(false);

        labelChick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chicken-small.png"))); // NOI18N
        labelChick.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelChick.setEnabled(false);
        labelChick.setMaximumSize(new java.awt.Dimension(150, 100));
        labelChick.setMinimumSize(new java.awt.Dimension(150, 100));

        labelPuppy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPuppy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dog-small.png"))); // NOI18N
        labelPuppy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelPuppy.setEnabled(false);

        labelDuck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDuck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/duck-small.jpg"))); // NOI18N
        labelDuck.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelDuck.setEnabled(false);

        labelRabbit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRabbit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rabbit-small.png"))); // NOI18N
        labelRabbit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelRabbit.setEnabled(false);

        labelCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cat-small.png"))); // NOI18N
        labelCat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelCat.setEnabled(false);

        labelPig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pig-small.png"))); // NOI18N
        labelPig.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelPig.setEnabled(false);

        cbChick.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbChick.setText("Chick");

        cbPuppy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbPuppy.setText("Puppy");

        cbDuck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDuck.setText("Duck");

        cbCat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCat.setText("Cat");

        cbRabbit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbRabbit.setText("Rabbit");

        cbPig.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbPig.setText("Pig");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDuck, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDuck, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelChick, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelRabbit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbChick, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRabbit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPig, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPuppy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPuppy, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPig, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbChick)
                    .addComponent(cbPuppy)
                    .addComponent(cbCat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPuppy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelChick, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDuck, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbRabbit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbPig, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRabbit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDuck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHOOSE YOUR PET");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckboxForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckboxForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckboxForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckboxForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckboxForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbCat;
    private javax.swing.JCheckBox cbChick;
    private javax.swing.JCheckBox cbDuck;
    private javax.swing.JCheckBox cbPig;
    private javax.swing.JCheckBox cbPuppy;
    private javax.swing.JCheckBox cbRabbit;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel labelCat;
    private javax.swing.JLabel labelChick;
    private javax.swing.JLabel labelDuck;
    private javax.swing.JLabel labelPig;
    private javax.swing.JLabel labelPuppy;
    private javax.swing.JLabel labelRabbit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object obj = e.getSource();
        if (obj.equals(cbCat)) {
            labelCat.setEnabled(!labelCat.isEnabled());
        } else if (obj.equals(cbChick)) {
            labelChick.setEnabled(!labelChick.isEnabled());
        } else if (obj.equals(cbDuck)) {
            labelDuck.setEnabled(!labelDuck.isEnabled());
        } else if (obj.equals(cbPuppy)) {
            labelPuppy.setEnabled(!labelPuppy.isEnabled());
        } else if (obj.equals(cbRabbit)) {
            labelRabbit.setEnabled(!labelRabbit.isEnabled());
        } else if (obj.equals(cbPig)) {
            labelPig.setEnabled(!labelPig.isEnabled());
        }

    }

    private void addActionListener() {
        cbCat.addActionListener(this);
        cbChick.addActionListener(this);
        cbDuck.addActionListener(this);
        cbPig.addActionListener(this);
        cbPuppy.addActionListener(this);
        cbRabbit.addActionListener(this);
    }
}
